export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';
export const CLEAR_PRODUCTS = 'CLEAR_PRODUCTS';

export const FETCH_SHOP = 'FETCH_SHOP';
export const FETCH_SHOP_SUCCESS = 'FETCH_SHOP_SUCCESS';
export const FETCH_SHOP_FAIL = 'FETCH_SHOP_FAIL';
export const CLEAR_SHOP = 'CLEAR_SHOP';
